### ISSUE TITLE
Error when importing image 

### ISSUE THREAD

**Issue by Hakkou3** [belijzajac/TermColor#6]
When trying to import an image into the program I get this following error: 
![image](https://user-images.githubusercontent.com/54744868/64065409-9ea89400-cc0d-11e9-88ad-aac73ef27768.png)

Running on Arch. Installing OpenCV from source didn't work so I installed opencv3-opt from the AUR, which did let me build TermColor properly.

**Comment by belijzajac** [comment]
I haven't tried reproducing the issue, however, I think I know what went wrong.

Could you please include `#include <iostream>` (at line 4) and `std::cerr << "location=" << picLocationStr << "\n";` (at line 27) in the `TermColor/src/ui/gui/widget/droparea/DropArea.cpp` file? Then recompile and run the program again. I wonder what the output will be (you can as well change your username in the output to something else if you don't want to show it)

![github_issue_01](https://user-images.githubusercontent.com/36075948/64079019-d0dbf380-ccea-11e9-839d-1f4ab982fa4b.png)

**Comment by belijzajac** [comment]
While testing TermColor around different desktop environments, I finally came across the issue and uploaded a fix. @Hakkou3 does it fix it for you?
